CREATE TABLE AUDITOR (
	EMPLOYEEID INT,
    LASTNAME VARCHAR(200),
    FIRSTNAME VARCHAR(200),
    PRIMARY KEY(EMPLOYEEID));

CREATE TABLE AUDIT_REPORT (
	AUDIT_REPORT_NUMBER VARCHAR(50),
    SECTOR VARCHAR(100),
    AUDIT_REPORT_DATE TIMESTAMP,
    AUDIT_START_DATE TIMESTAMP NULL,
    AUDIT_END_DATE TIMESTAMP NULL,
    AUDIT_TYPE VARCHAR(100),
    PRIMARY KEY(AUDIT_REPORT_NUMBER));
    
CREATE TABLE AUDITOR_REPORT (
	EMPLOYEEID INT,
    AUDIT_REPORT_NUMBER VARCHAR(50),
    PRIMARY KEY(EMPLOYEEID, AUDIT_REPORT_NUMBER));
    
CREATE TABLE FINDING (
	FINDING_ID VARCHAR(50),
    CREATE_DATE varchar(50),
    STATUS VARCHAR(100),
    RISK_TYPE VARCHAR(200),
    SEVERITY VARCHAR(50),
    PROBABILITY INT,
    EFFECT INT,
    AUDIT_REPORT_NUMBER VARCHAR(50),
    PRIMARY KEY(FINDING_ID));

  

CREATE TABLE PROCESS (
	PROCESSID INT,
    PROCESSNAME VARCHAR(200),
    PRIMARY KEY(PROCESSID));
  
  CREATE TABLE AUDIT_PROCESS(
	PROCESSID INT,
    AUDIT_REPORT_NUMBER VARCHAR(50),
    PRIMARY KEY(PROCESSID, AUDIT_REPORT_NUMBER));    

CREATE TABLE SUB_PROCESS (
	SUB_PROCESS_ID INT,
    SUB_PROCESS_NAME VARCHAR (200),
    PROCESSID INT,
    PRIMARY KEY(SUB_PROCESS_ID));

CREATE TABLE TIMESHEET (
	ID INT,
    EMPLOYEEID INT,
    CREATE_DATE varchar(50),
    TOPIC VARCHAR(300),
    WORKING_HOURS NUMERIC,
    CATEGORY VARCHAR(200),
    SUB_CATEGORY VARCHAR(200),
    DETAIL VARCHAR(500),
    PRIMARY KEY(ID));